# Site settings
title: ATS Engineering
email: engineering@atsid.com
description: > # this means to ignore newlines until "baseurl:"
  ATS software engineering culture and practices
baseurl: "/engineering" # the subpath of your site, e.g. /blog/
url: "http://labs.atsid.com" # the base hostname & protocol for your site
github_username:  atsid

# Build settings
markdown: kramdown
