# Site settings
title: Software Delivery
email: engineering@atsid.com
description: > # this means to ignore newlines until "baseurl:"
  ATS software delivery culture and practices
baseurl: "/engineering" # the subpath of your site, e.g. /blog/
url: "http://labs.atsid.com" # the base hostname & protocol for your site
github_username:  atsid
twitter_username:  ats_inc

# Build settings
markdown: kramdown
